<div class="topnav">
    <a class="<?php echo ($page == 'home') ? 'active' : ''; ?>" href="index.php">Home</a>

    <a class="<?php echo ($page == 'apply') ? 'active' : ''; ?>" href="apply.php">Apply Now</a>

    <a class="<?php echo ($page == 'jobs') ? 'active' : ''; ?>" href="jobs.php">Jobs</a>

    <a class="<?php echo ($page == 'about') ? 'active' : ''; ?>" href="about.php">About Us</a>

    <a class="<?php echo ($page == 'manage') ? 'active' : ''; ?>" href="login.php">Management</a>
</div>
